apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component_name }}
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.service.component_name }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.service.containerPort }}